### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jeeyung** [jeeyung/visualization_project#1]
- [x] t-sne output 출력 -지영
- [x]  [클러스터링 시각화](http://bl.ocks.org/feyderm/75c18a9143aac50a24e392762f10d6a4) + 클릭 이벤트 -지혜

- [ ] 트리맵-지영
   - hi1-cluster/2-충돌상황/3-성별, 연령대, 과실자 상태, 부상정도, 시간대

- [x] 클러스터링 시각화, bar chart, 트리맵, map 합치기 + 레이아웃 조정
- [ ] 발표자료 만들기

- [x] 전처리 (위도, 경도 추가) -지혜
- [x] 막대그래프-지영
   - row count (성별, 연령대, 과실자 상태, 부상정도, 시간대)
- [x] map-지혜
   - 사고 건수

**Comment by sophia-jihye** [comment]
연령대 구분 기준: 9세 이하, 10대, 20대, 30대, 40대, 50대, 60대, 70대, 80대 이상
시간대 구분 기준: 자정-새벽6시, 새벽6시-낮12시, 낮12시 - 오후6시, 오후6시-자정
